name = "Developers Dungeon SMP"
version = "v0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef021f716a277eda44beeb4e9a68246db49f8f50904801eb2eded91379c932a7"

[versions]
fabric = "0.16.2"
minecraft = "1.21.1"
